version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://admin:admindb@footballmatchesdb.ywjx4tg.mongodb.net/?retryWrites=true&w=majority
    command: sh -c "pdm run uvicorn main:app --host 0.0.0.0 --port 8000"
